<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AFH.AdviserInsights.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AFH.AdviserInsights.Application\AFH.AdviserInsights.Application.csproj" />
    <ProjectReference Include="..\AFH.AdviserInsights.Contract\AFH.AdviserInsights.Contract.csproj" />
    <ProjectReference Include="..\AFH.AdviserInsights.Domain\AFH.AdviserInsights.Domain.csproj" />
  </ItemGroup>
</Project>
