<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.51.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.50.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" />
  </ItemGroup>

  <ItemGroup>
    <None Include="host.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="local.settings.template.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AFH.AdviserInsights.Application\AFH.AdviserInsights.Application.csproj" />
    <ProjectReference Include="..\AFH.AdviserInsights.Infrastructure\AFH.AdviserInsights.Infrastructure.csproj" />
    <ProjectReference Include="..\AFH.AdviserInsights.Contract\AFH.AdviserInsights.Contract.csproj" />
    <ProjectReference Include="..\..\..\..\sdk\afh-common-error\src\AFH.Common.Errors.AzureFunctions\AFH.Common.Errors.AzureFunctions.csproj" />
  </ItemGroup>
</Project>
